job('First_Maven_Job_Via_DSL') {
    description("First maven job generated by DSL on ${new Date()}, this is a test project hosted on github")
    scm {
        git("https://github.com/EnggAnkit/Coolhand.git", 'master')
    }
    triggers {
        scm('* * * * *')
    }
    steps {
        maven('clean package', 'maven-samples/single-module/pom.xml')
    }
    publishers {
        //archive the war file generated
        archiveArtifacts '**/*.war'
    }
}    
